PLANTS = [
    ('Аир обыкновенный (болотный)', 'https://www.plantarium.ru/page/view/item/664.html', 1),
    ('Алтей лекарственный', 'https://www.plantarium.ru/page/view/item/2417.html', 1),
    ('Багульник болотный', 'https://www.plantarium.ru/page/view/item/22241.html', 1),
    ('Бадан толстолистный', 'https://www.plantarium.ru/page/view/item/6418.html', 1),
    ('Баранец обыкновенный', 'https://www.plantarium.ru/page/view/item/20324.html', 1),
    ('Бессмертник песчаный', 'https://www.plantarium.ru/page/view/item/18366.html', 1),
    ('Борец (аконит) белоустый', 'https://www.plantarium.ru/page/samples/taxon/44226.html', 1),
    ('Валериана лекарственная', 'https://www.plantarium.ru/page/view/item/39858.html', 1),
    ('Вахта трехлистная', 'https://www.plantarium.ru/page/view/item/24291.html', 1),
    ('Вздутоплодник сибирский', 'https://www.plantarium.ru/page/view/item/27704.html', 1),
    ('Володушка золотистая', 'https://www.plantarium.ru/page/view/item/7158.html', 1),
    ('Гамамелис виргинский', 'https://www.plantarium.ru/page/view/item/46184.html', 1),
    ('Дурман обыкновенный', 'https://www.plantarium.ru/page/view/item/12728.html', 1),
    ('Душица обыкновенная', 'https://www.plantarium.ru/page/view/item/25797.html', 1),
    ('Желтушник раскидистый', 'https://www.plantarium.ru/page/view/item/71448.html', 1),
    ('Жостер слабительный', 'https://www.plantarium.ru/page/view/item/31639.html', 1),
    ('Катарантус розовый', 'https://www.plantarium.ru/page/view/item/45738.html', 1),
    ('Копеечник альпийский', 'https://www.plantarium.ru/page/view/item/18108.html', 1),
    ('Крушина ольховидная', 'https://www.plantarium.ru/page/view/item/16521.html', 1),
    ('Лабазник вязолистный', 'https://www.plantarium.ru/page/view/item/16470.html', 1),
    ('Леспедеца двуцветная', 'https://www.plantarium.ru/page/view/item/22487.html', 1),
    ('Наперстянка шерстистая', 'https://www.plantarium.ru/page/view/item/13287.html', 0),
    ('Одуванчик лекарственный', 'https://www.plantarium.ru/page/view/item/37740.html', 1),
    ('Очиток большой', 'https://www.plantarium.ru/page/view/item/34967.html', 1),
    ('Пижма обыкновенная', 'https://www.plantarium.ru/page/view/item/37406.html', 1),
    ('Пион уклоняющийся', 'https://www.plantarium.ru/page/view/item/26648.html', 1),
    ('Пихта сибирская, белокорая', 'https://www.plantarium.ru/page/view/item/20.html', 0),
    ('Подорожник блошиный', 'https://www.plantarium.ru/page/view/item/28614.html', 1),
    ('Подофилл щитовидный', 'https://www.plantarium.ru/page/view/item/47777.html', 1),
    ('Полынь горькая', 'https://www.plantarium.ru/page/view/item/3793.html', 1),
    ('Пустырник сердечный', 'https://www.plantarium.ru/page/view/item/22350.html', 1),
    ('Родиола розовая', 'https://www.plantarium.ru/page/view/item/44512.html', 1),
    ('Синюха голубая', 'https://www.plantarium.ru/page/view/item/29149.html', 1),
    ('Скумпия кожевенная', 'https://www.plantarium.ru/page/view/item/11420.html', 1),
    ('Смоковница обыкновенная', 'https://www.plantarium.ru/page/view/item/16413.html', 1),
    ('Солодка голая', 'https://www.plantarium.ru/page/view/item/17684.html', 1),
    ('Сумах дубильный', 'https://www.plantarium.ru/page/view/item/44936.html', 1),
    ('Сушеница топяная', 'https://www.plantarium.ru/page/view/item/17714.html', 1),
    ('Термопсис ланцетный', 'https://www.plantarium.ru/page/view/item/38164.html', 1),
    ('Тимьян обыкновенный', 'https://www.plantarium.ru/page/view/item/59252.html', 1),
    ('Тмин обыкновенный', 'https://www.plantarium.ru/page/view/item/9207.html', 1),
    ('Толокнянка обыкновенная', 'https://www.plantarium.ru/page/view/item/3573.html', 1),
    ('Тыква обыкновенная', 'https://www.plantarium.ru/page/view/item/12175.html', 1),
    ('Тысячелистник обыкновенный', 'https://www.plantarium.ru/page/view/item/319.html', 1),
    ('Фенхель обыкновенный', 'https://www.plantarium.ru/page/view/item/16499.html', 1),
    ('Фиалка трехцветная', 'https://www.plantarium.ru/page/view/item/40811.html', 1),
    ('Хвощ полевой', 'https://www.plantarium.ru/page/view/item/14673.html', 1),
    ('Хмель обыкновенный', 'https://www.plantarium.ru/page/view/item/20316.html', 1),
    ('Тимьян ползучий', 'https://www.plantarium.ru/page/view/item/38454.html', 1),
    ('Чемерица лобеля', 'https://www.plantarium.ru/page/view/item/39977.html', 1),
    ('Череда трехраздельная', 'https://www.plantarium.ru/page/view/item/6663.html', 1),
    ('Чистотел большой', 'https://www.plantarium.ru/page/view/item/10130.html', 1),
    ('Шалфей лекарственны', 'https://www.plantarium.ru/page/view/item/33522.html', 1),
    ('Шиповник майский', 'https://www.plantarium.ru/page/view/item/32327.html', 1),
    ('Шлемник байкальский', 'https://www.plantarium.ru/page/view/item/34695.html', 1),
    ('Щавель конский', 'https://www.plantarium.ru/page/view/item/32758.html', 1),
    ('Якорцы стелющиеся', 'https://www.plantarium.ru/page/view/item/38895.html', 1),
]


CATEGORIES = [
    'Описание',
    'Другие виды',
    'Ареал',
    'Экология',
    'Ресурсы',
    'Возделывание',
    'Сырьё',
    'Химический состав',
    'Фармакологические свойства',
    'Применение в медицине',
    # 'Литература'
]

REGIONS = {
    'Центральный федеральный округ': [
        'Белгородская область', 'Брянская область', 'Владимирская область',
        'Воронежская область', 'Ивановская область', 'Калужская область',
        'Костромская область', 'Курская область', 'Липецкая область',
        'Московская область', 'Орловская область', 'Рязанская область',
        'Смоленская область', 'Тамбовская область', 'Тверская область',
        'Тульская область', 'Ярославская область', 'г. Москва'
    ],
    'Северо-Западный федеральный округ': [
        'Республика Карелия', 'Республика Коми', 'Архангельская область',
        'Вологодская область', 'Калининградская область',
        'Ленинградская область', 'Мурманская область', 'Новгородская область',
        'Псковская область', 'г. Санкт-Петербург'
    ],
    'Южный федеральный округ': [
        'Республика Адыгея',
        'Республика Дагестан',
        'Республика Ингушетия',
        'Кабардино-Балкарская Республика',
        'Республика Калмыкия',
        'Карачаево-Черкесская Республика',
        'Республика Северная Осетия - Алания',
        'Чеченская Республика',
        'Краснодарский край',
        'Ставропольский край',
        'Астраханская область',
        'Волгоградская область',
        'Ростовская область',
    ],
    'Приволжский федеральный округ': [
        'Республика Башкортостан',
        'Республика Марий Эл',
        'Республика Мордовия',
        'Республика Татарстан',
        'Удмуртская Республика',
        'Чувашская Республика',
        'Кировская область',
        'Нижегородская область',
        'Оренбургская область',
        'Пензенская область',
        'Пермская область',
        'Самарская область',
        'Саратовская область',
        'Ульяновская область',
    ],
    'Уральский федеральный округ': [
        'Курганская область',
        'Свердловская область',
        'Тюменская область',
        'Ханты-Мансийский автономный округ - Югра',
        'Ямало-Ненецкий автономный округ',
    ],
    'Сибирский федеральный округ': [
        'Республика Алтай',
        'Республика Бурятия',
        'Республика Тыва',
        'Республика Хакасия',
        'Алтайский край',
        'Красноярский край',
        'Эвенкийский автономный округ',
        'Иркутская область',
        'Кемеровская область',
        'Новосибирская область',
        'Омская область',
        'Томская область',
        'Читинская область',
    ],
    'Дальневосточный федеральный округ': [
        'Республика Саха (Якутия)',
        'Приморский край',
        'Хабаровский край',
        'Амурская область',
        'Камчатская область',
        'Корякский автономный округ',
        'Магаданская область',
        'Сахалинская область',
        'Еврейская автономная область',
        'Чукотский автономный округ',
    ]
}
import yaml
with open("../data/dataset/data.yml", "r", encoding='utf-8') as stream:
    try:
        PLANTS_INFO = yaml.safe_load(stream)
    except yaml.YAMLError as exc:
        print(exc)